### ISSUE TITLE
mechanic: Basic AI State Machine

### ISSUE THREAD

**Issue by Illusivebyte** [ImpostorSyndromeAnonymous/GameOff-2022#14]
# Game Mechanic

## Mechanic Description
**A clear and concise description of the mechanic.**
The basic state machine for the enemy AI.

## Game Play Example 
**Provide a simple example of the mechanic in the context of the game.**
The player ends their turn and the enemy AI take their turns, each selecting an objective. They move towards beneficial items/positions, attack other AIs or the Player, and use the various items they pickup.

## Additional context
**Add any other context or screenshots about the game play mechanic here.**
This is the first, most basic implementation. Advanced behaviors will be apart of a later ticket

**Comment by Illusivebyte** [comment]
blocked by #15

**Comment by dracoranger** [comment]
Basic AI complete
The AI will search for an enemy, move towards them, and attack
