### ISSUE TITLE
mechanic: Basic Path Finding

### ISSUE THREAD

**Issue by Illusivebyte** [ImpostorSyndromeAnonymous/GameOff-2022#15]
# Game Mechanic

## Mechanic Description
**A clear and concise description of the mechanic.**
AI are able to perform path finding based on the current environment, hazards, platforms, and their limited stamina.

## Game Play Example 
**Provide a simple example of the mechanic in the context of the game.**
After a player ends their turn the AI enemy to move towards advantageous items or positions in both the horizontal and vertical axis. 

## Additional context
**Add any other context or screenshots about the game play mechanic here.**
N/A

**Comment by dracoranger** [comment]
Basic pathfinding through A* is complete
