### ISSUE TITLE
sound: Main Menu Musical Theme

### ISSUE THREAD

**Issue by Illusivebyte** [ImpostorSyndromeAnonymous/GameOff-2022#8]
# New Sound Asset

## Sound Description
**A clear and concise description of the sound asset.**
A catchy and unique musical theme for the game.

## Use Case
**How will this asset be used in the game?**
Played in the Main Menu scene on loop during character and level selection.

## Style Requirements
**Are there any style requirements for this asset?**
8-bit.

## Additional Context
**Add any other context about the sound here.**
N/A

**Comment by michael-benedetti** [comment]
Found a sweet tool to at least prototype music, maybe completely jam it out depending on how lazy I'm feeling. 

Potential menu theme candidate:

https://www.beepbox.co/#9n31sbk0l00e07t2ma7g0fj07r1i0o432T1v1uc4f0q8111d23A0F4B4Q5000Pff00E0T7v1u70f40p61770q72f5q0E21990l65d06HT-SRJJJJIAAAAAh0IaE1c11T6v1u06f10s4q011d08W7E0T4v1uf0f0q011z6666ji8k8k3jSBKSJJAArriiiiii07JCABrzrrrrrrr00YrkqHrsrrrrjr005zrAqzrjzrrqr1jRjrqGGrrzsrsA099ijrABJJJIAzrrtirqrqjqixzsrAjrqjiqaqqysttAJqjikikrizrHtBJJAzArzrIsRCITKSS099ijrAJS____Qg99habbCAYrDzh00E0b0000000000000i4M0000004h8h0000004h4h4g00000p221FBRxEFEYczE8XWGpczFH8M5d7HbzzUagGFFHbZ2AU-KKFdBUFvjh-2ewzAo0zOzzMiZd7H4tQ2t_bWyeCGEzE8Wa2eywz0IQpM0zsQpJx9EM0zKG8SqcXyfuXdWUzG8M0
